### PR TITLE
Metadata: Fix return value for Metadata::get when `$single` is true

### LINKED ISSUE #76: `metadata_exists` returns `true` even when the meta key doesn't exist.
Steps:
- Check `metadata_exists` for a valid post ID - `metadata_exists( 'post', $post_id, 'non-existing-key' )`
- Confirm that it returns `true`

It seems that because of this

https://github.com/Automattic/wordbless/blob/bd206dbf4c43d58c6c705a6069fd23ed54641eb0/src/Metadata.php#L82

`metadata_exists` in Core bails early because of [this logic](https://github.com/WordPress/wordpress-develop/blob/50fb4086b7afbfa012c5d1f2eeff79b1bae3b00e/src/wp-includes/meta.php#L749-L752)

```php
$check = apply_filters( "get_{$meta_type}_metadata", null, $object_id, $meta_key, true, $meta_type );
if ( null !== $check ) {
	return (bool) $check;
}
```

And that `(bool) $check` becomes `true` for that being a non-empty array.

A solution would be to return `null` instead of `array( '' )`

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Fixes #76

Use [`get_metadata_default`](https://developer.wordpress.org/reference/functions/get_metadata_default/) to get the default meta value instead of hard-coding it.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -2,3 +2,5 @@
 /tools/
 /vendor/
 /wordpress/
+
+.phpunit.result.cache
```
Comment (manzoorwanijk) [inline .gitignore]: Missing EOL

```suggestion
.phpunit.result.cache

```

**Comment by manzoorwanijk** [comment]
As a follow up, we can improve it further like #65

File: src/Metadata.php [hunk 2]
```diff
@@ -78,8 +78,8 @@ public function get( $check, $object_id, $meta_key, $single ) {
 				}
 			}
 		}
-		if ( empty( $check ) && $single ) {
-			$check = array( '' ); // Ensure an empty string is returned when meta is not found.
+		if ( empty( $check ) ) {
+			$check = get_metadata_default( $this->meta_type, $object_id, $meta_key, $single );
```
Comment (szepeviktor) [inline src/Metadata.php]:
```suggestion
			return get_metadata_default( $this->meta_type, $object_id, $meta_key, $single );
```

It is nice to be straight-forward.

Comment (manzoorwanijk) [reply src/Metadata.php]: Done. Thanks

**Comment by kraftbj** [comment]
This looks good to me. @szepeviktor, if you're happy with the revision after your review, good to merge.

**Review by szepeviktor — APPROVED** [review]
